### ISSUE TITLE
MetaDrive env: "AttributeError: 'NoneType' object has no attribute 'reset'"

### ISSUE THREAD

**Issue by OscarBastardo** [Replicable-MARL/MARLlib#78] opened 2023-01-31 12:38 UTC
Hello,

I am trying to run an algorithm on a MetaDrive environment as follows:
```
python marl/main.py --algo_config=mappo --env_config=metadrive with env_args.map_name=Roundabout
```

I have installed the MetaDrive environment as per the documentation:
```
pip install metadrive-simulator==0.2.3
```

But I get the following error after training for some time:
```
2023-01-31 09:56:28,733 ERROR trial_runner.py:924 -- Trial MAPPOTrainer_metadrive_Roundabout_45631_00000: Error processing event.
Traceback (most recent call last):
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 890, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::MAPPOTrainer.train_buffered() (pid=20470, ip=192.168.0.98, repr=MAPPOTrainer)
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 224, in train_buffered
    result = self.train()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 682, in train
    raise e
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 668, in train
    result = Trainable.train(self)
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 283, in train
    result = self.step()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 240, in step
    evaluation_metrics = self.evaluate()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 958, in evaluate
    self.evaluation_workers.local_worker().sample()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 753, in sample
    batches = [self.input_reader.next()]
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 103, in next
    batches = [self.get_data()]
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 233, in get_data
    item = next(self._env_runner)
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 586, in _env_runner
    base_env.poll()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 422, in poll
    obs[i], rewards[i], dones[i], infos[i] = env_state.poll()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 478, in poll
    self.reset()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 528, in reset
    self.last_obs = self.env.reset()
  File "/home/oscar/msc/MARLlib/envs/base_env/metadrive.py", line 69, in reset
    original_obs = self.env.reset()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/metadrive/envs/base_env.py", line 291, in reset
    self.engine.reset()
AttributeError: 'NoneType' object has no attribute 'reset'
```

Any guidance would be appreciated,
Thanks.

**Comment by Theohhhu** [comment] 2023-02-02 09:29
This is not a bug. We don't support MAPPO in Metadrive. Only independent learning algorithms (e.g. IPPO) are available.

Main reason: the agent number is not fixed in metadrive (e.g. crashed cars are wiped out before the end of the game). Thus the input dimension of centralized critic function is always changing. This is unacceptable. 

There may exist solutions such as mean field-based MAPPO. While it goes far beyond MARLlib's original intention on building algorithms which is not too task specific. 

You can try -`-algo_config=ppo` to test if the metadrive installation is ok.

Any further concern is welcome.

**Comment by OscarBastardo** [comment] 2023-02-03 10:07
> This is not a bug. We don't support MAPPO in Metadrive. Only independent learning algorithms (e.g. IPPO) are available.
> 
> Main reason: the agent number is not fixed in metadrive (e.g. crashed cars are wiped out before the end of the game). Thus the input dimension of centralized critic function is always changing. This is unacceptable.
> 
> There may exist solutions such as mean field-based MAPPO. While it goes far beyond MARLlib's original intention on building algorithms which is not too task specific.
> 
> You can try -`-algo_config=ppo` to test if the metadrive installation is ok.
> 
> Any further concern is welcome.

I see, thank you for the clarification on algorithms supported in MetaDrive.

As suggested I tried the IPPO algorithm, but I get the same error.

```
Failure # 1 (occurred at 2023-02-03_09-35-27)
Traceback (most recent call last):
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 890, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): [36mray::IPPOTrainer.train_buffered()[39m (pid=39673, ip=192.168.0.98, repr=IPPOTrainer)
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 224, in train_buffered
    result = self.train()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 682, in train
    raise e
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 668, in train
    result = Trainable.train(self)
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 283, in train
    result = self.step()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 240, in step
    evaluation_metrics = self.evaluate()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 958, in evaluate
    self.evaluation_workers.local_worker().sample()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 753, in sample
    batches = [self.input_reader.next()]
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 103, in next
    batches = [self.get_data()]
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 233, in get_data
    item = next(self._env_runner)
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 586, in _env_runner
    base_env.poll()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 422, in poll
    obs[i], rewards[i], dones[i], infos[i] = env_state.poll()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 478, in poll
    self.reset()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 528, in reset
    self.last_obs = self.env.reset()
  File "/home/oscar/msc/MARLlib/envs/base_env/metadrive.py", line 69, in reset
    original_obs = self.env.reset()
  File "/home/oscar/anaconda3/envs/marllib/lib/python3.8/site-packages/metadrive/envs/base_env.py", line 291, in reset
    self.engine.reset()
AttributeError: 'NoneType' object has no attribute 'reset'
```

Note that the initial check for the environment installation seems OK.

```
Successfully registered the following environments: ['MetaDrive-test-v0', 'MetaDrive-validation-v0', 'MetaDrive-v0', 'MetaDrive-10envs-v0', 'MetaDrive-1000envs-v0', 'MetaDrive-training0-v0', 'MetaDrive-training1-v0', 'MetaDrive-training2-v0'].
+------------+----------------+-------------------------------------+-------------------------------------+----------------------------+
| Env_Name   | Check_Status   | Error_Log                           | Config_File_Location                | Env_File_Location          |
+============+================+=====================================+=====================================+============================+
| mpe        | Error          | No module named 'numpy.typing'      | envs/base_env/config/mpe.yaml       | envs/base_env/mpe.py       |
+------------+----------------+-------------------------------------+-------------------------------------+----------------------------+
| mamujoco   | Error          | No module named 'multiagent_mujoco' | envs/base_env/config/mamujoco.yaml  | envs/base_env/mamujoco.py  |
+------------+----------------+-------------------------------------+-------------------------------------+----------------------------+
| smac       | Error          | No module named 'smac'              | envs/base_env/config/smac.yaml      | envs/base_env/smac.py      |
+------------+----------------+-------------------------------------+-------------------------------------+----------------------------+
| football   | Error          | No module named 'gfootball'         | envs/base_env/config/football.yaml  | envs/base_env/football.py  |
+------------+----------------+-------------------------------------+-------------------------------------+----------------------------+
| magent     | Error          | No module named 'numpy.typing'      | envs/base_env/config/magent.yaml    | envs/base_env/magent.py    |
+------------+----------------+-------------------------------------+-------------------------------------+----------------------------+
| rware      | Error          | No module named 'rware'             | envs/base_env/config/rware.yaml     | envs/base_env/rware.py     |
+------------+----------------+-------------------------------------+-------------------------------------+----------------------------+
| lbf        | Error          | No module named 'lbforaging'        | envs/base_env/config/lbf.yaml       | envs/base_env/lbf.py       |
+------------+----------------+-------------------------------------+-------------------------------------+----------------------------+
| pommerman  | Error          | No module named 'pommerman'         | envs/base_env/config/pommerman.yaml | envs/base_env/pommerman.py |
+------------+----------------+-------------------------------------+-------------------------------------+----------------------------+
| hanabi     | Error          | No module named 'cffi'              | envs/base_env/config/hanabi.yaml    | envs/base_env/hanabi.py    |
+------------+----------------+-------------------------------------+-------------------------------------+----------------------------+
| metadrive  | Ready          | Null                                | envs/base_env/config/metadrive.yaml | envs/base_env/metadrive.py |
```

**Comment by Theohhhu** [comment] 2023-02-13 05:38
Could you pls share your params.json file for us to check?
By the way, does this bug appear after some training iterations or just early stop before the training starts?

**Comment by OscarBastardo** [comment] 2023-02-13 08:35
> Could you pls share your params.json file and list of packages you installed for us to check? By the way, does this bug appear after some training iterations or just early stop before the training starts?

Thanks for the reply. Sure, here's the params.json
```
{
  "batch_mode": "complete_episodes",
  "clip_param": 0.3,
  "entropy_coeff": 0.01,
  "env": "metadrive_Roundabout",
  "evaluation_interval": 10,
  "framework": "torch",
  "kl_coeff": 0.2,
  "lambda": 1.0,
  "lr": 0.0005,
  "model": {
    "custom_model": "Base_Model",
    "custom_model_config": {
      "algo_args": {
        "batch_episode": 10,
        "batch_mode": "complete_episodes",
        "clip_param": 0.3,
        "entropy_coeff": 0.01,
        "kl_coeff": 0.2,
        "lambda": 1.0,
        "lr": 0.0005,
        "num_sgd_iter": 5,
        "use_gae": true,
        "vf_clip_param": 10.0,
        "vf_loss_coeff": 1.0
      },
      "algorithm": "ppo",
      "env": "metadrive",
      "env_args": {
        "crash_done": true,
        "map_name": "Roundabout",
        "num_agents": 5,
        "start_seed": 0
      },
      "episode_limit": 200,
      "evaluation_interval": 10,
      "framework": "torch",
      "global_state_flag": false,
      "local_mode": false,
      "mask_flag": false,
      "model_arch_args": {
        "core_arch": "gru",
        "fc_layer": 1,
        "hidden_state_size": 256,
        "out_dim_fc_0": 128
      },
      "num_agents": 5,
      "num_cpus_per_worker": 1,
      "num_gpus": 1,
      "num_gpus_per_worker": 0,
      "num_workers": 0,
      "opp_action_in_cc": false,
      "policy_mapping_info": {
        "all_scenario": {
          "all_agents_one_policy": true,
          "description": "metadrive all scenarios",
          "one_agent_one_policy": true,
          "team_prefix": [
            "agent_"
          ]
        }
      },
      "seed": 123,
      "share_policy": "group",
      "space_act": "Box([-1. -1.], [1. 1.], (2,), float32)",
      "space_obs": "Dict(obs:Box([-0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.\n -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.\n -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.\n -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.\n -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.\n -0.], [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], (91,), float32))",
      "stop_iters": 9999999,
      "stop_reward": 999999,
      "stop_timesteps": 2000000
    },
    "max_seq_len": 200
  },
  "multiagent": {
    "policies": "{'shared_policy'}",
    "policy_mapping_fn": "<function run_il.<locals>.<lambda> at 0x7fb5303e6550>"
  },
  "num_gpus": 1,
  "num_gpus_per_worker": 0,
  "num_sgd_iter": 5,
  "num_workers": 0,
  "sgd_minibatch_size": 2000,
  "simple_optimizer": false,
  "train_batch_size": 2000,
  "use_gae": true,
  "vf_clip_param": 10.0,
  "vf_loss_coeff": 1.0
}
```

The list of packages via `pip freeze`
```
asttokens==2.2.1
async-timeout==4.0.2
attrs==22.2.0
certifi @ file:///croot/certifi_1671487769961/work/certifi
charset-normalizer==3.0.1
click==8.1.3
cloudpickle==1.6.0
colorama==0.4.6
contourpy==1.0.7
cycler==0.11.0
Cython==0.29.6
dm-tree==0.1.8
exceptiongroup==1.1.0
executing==1.2.0
filelock==3.9.0
fonttools==4.38.0
grpcio==1.51.1
gym==0.19.0
gym-notices==0.0.8
gymnasium==0.27.1
gymnasium-notices==0.0.1
icecream==2.1.3
idna==3.4
imageio==2.25.0
importlib-metadata==4.13.0
importlib-resources==5.10.2
iniconfig==2.0.0
jax-jumpy==0.2.0
jsonschema==4.17.3
kiwisolver==1.4.4
lxml==4.9.2
lz4==4.3.2
-e git+https://github.com/Replicable-MARL/MARLlib.git@e1ddcef519b5d6736f140bcf8ad75689de62bff7#egg=marllib
matplotlib==3.6.3
metadrive-simulator==0.2.3
msgpack==1.0.4
networkx==3.0
numpy==1.19.3
opencv-python-headless==4.7.0.68
packaging==23.0
Panda3D==1.10.8
panda3d-gltf==0.13
panda3d-simplepbr==0.10
pandas==1.4.4
Pillow==9.4.0
pkgutil_resolve_name==1.3.10
pluggy==1.0.0
protobuf==3.20.1
pygame==2.1.2
Pygments==2.14.0
pyparsing==3.0.9
pyrsistent==0.19.3
pytest==7.2.1
python-dateutil==2.8.2
pytz==2022.7.1
PyWavelets==1.4.1
PyYAML==6.0
ray==1.8.0
redis==4.4.2
requests==2.28.2
scikit-image==0.19.3
scipy==1.10.0
seaborn==0.12.2
six==1.16.0
SuperSuit==3.7.1
tabulate==0.9.0
tensorboardX==2.5.1
tifffile==2023.1.23.1
tomli==2.0.1
torch==1.9.1
tqdm==4.64.1
typing_extensions==4.4.0
urllib3==1.26.14
yapf==0.30.0
zipp==3.12.0
```

The bug appears after some training iterations. It seems to occur after the 9th training iteration and given `"evaluation_interval": 10` from params.json, it seems to be an issue with the evaluation process.

**Comment by ggstar00** [comment] 2023-02-14 16:40
same error

**Comment by Theohhhu** [comment] 2023-02-16 06:09
Change `num_workers` in `ray.yaml` to >2,e.g. 5 to see if the bug still there.
Metadrive requires additional workers (at least 1) to do the evaluation.

**Comment by OscarBastardo** [comment] 2023-02-17 09:26
> Change `num_workers` in `ray.yaml` to >2,e.g. 5 to see if the bug still there. Metadrive requires additional workers (at least 1) to do the evaluation.

Hi, I tried with `num_workers: 5` and training ran for the set number of timesteps.

**Closed** 2023-02-18 04:29 UTC
Labels: bug
